// Publishes the built single-file page to where GitHub Pages serves it.
//
// The portfolio has no CI — Pages serves committed files as-is — so the
// playable page has to be prebuilt and committed: games/pinball/pinball.html.
// Vite builds into dist/ (scratch, gitignored locally); this copies the one
// inlined HTML file up and swaps the dev-entry comment for a generated-file one.

import { readFileSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const built = join(root, 'dist', 'index.html');
if (!existsSync(built)) throw new Error('No dist/index.html — run `vite build` before releasing.');

const DEV_ENTRY_COMMENT = '<!-- Vite dev-server entry (npm run dev). Not the deployed page — that\'s pinball.html, generated from this via `npm run build`. -->';
const RELEASED_COMMENT = '<!-- Generated by scripts/release.mjs from dist/index.html. Do not hand-edit — edit index.html / src/ and re-run `npm run build`. -->';

const html = readFileSync(built, 'utf8');
if (!html.includes(DEV_ENTRY_COMMENT)) throw new Error('dev-entry comment missing from dist/index.html — keep index.html and release.mjs in sync.');
writeFileSync(join(root, 'pinball.html'), html.replace(DEV_ENTRY_COMMENT, RELEASED_COMMENT));
rmSync(join(root, 'dist'), { recursive: true, force: true });

const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
console.log(`Released: pinball.html (${kb} KB, self-contained)`);
