/* Browser-shaped integration harness for simultaneous pointers and cancellation.
   Complements real browser visual/audio checks; it is not a browser substitute. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(),listeners={},stored=new Map();let nextFrame;
const gradient={addColorStop(){}};
const drawing=new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get(o,k){return o[k]??(()=>{});},set(o,k,v){o[k]=v;return true;}});
function element(id){if(elements.has(id))return elements.get(id);const e={id,handlers:{},dataset:{},style:{},hidden:true,value:0,checked:false,textContent:'',attrs:{},captured:new Set(),classList:{toggle(){}},addEventListener(name,fn){this.handlers[name]=fn;},setAttribute(k,v){this.attrs[k]=v;},getBoundingClientRect:()=>({left:0,top:0,width:1000,height:700}),getContext:()=>drawing,focus(){},setPointerCapture(i){this.captured.add(i);},hasPointerCapture(i){return this.captured.has(i);},releasePointerCapture(i){this.captured.delete(i);},emit(type,ev={}){this.handlers[type]?.({target:this,preventDefault(){},...ev});}};elements.set(id,e);return e;}
const context={console,Math,location:{protocol:'http:'},window:{devicePixelRatio:1,addEventListener:(k,f)=>listeners[k]=f},document:{hidden:false,getElementById:element,body:element('body'),addEventListener:(k,f)=>listeners['document:'+k]=f},localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,String(v))},matchMedia:()=>({matches:false}),ResizeObserver:class{observe(){}},Image:class{constructor(){this.complete=true;this.naturalWidth=1536;this.naturalHeight=1024;}},requestAnimationFrame:f=>nextFrame=f};
vm.createContext(context);for(const name of ['physics','audio','wildlife','render','main'])vm.runInContext(fs.readFileSync(__dirname+'/'+name+'.js','utf8'),context,{filename:name+'.js'});
const api=context.window.tinwater,canvas=element('scene');let now=100;
function frame(n=1){for(let i=0;i<n;i++){now+=1000/60;nextFrame(now);}}
function screen(x,y){return {clientX:api.renderer.ox+x*api.renderer.scale,clientY:api.renderer.oy+y*api.renderer.scale};}
function pointer(id,x,y,kind='pointerdown'){canvas.emit(kind,{pointerId:id,pointerType:'touch',...screen(x,y)});}
frame();pointer(1,740,160);pointer(2,847,300);frame();assert.equal(api.getState().cups.filter(c=>c.held).length,2,'Independent simultaneous holds');pointer(1,780,210,'pointermove');frame(10);assert.ok(api.sim.cups[0].angle>.3);canvas.emit('pointercancel',{pointerId:1});frame();assert.equal(api.sim.cups[0].held,false);assert.equal(api.sim.cups[1].held,true);canvas.emit('lostpointercapture',{pointerId:2});frame();assert.equal(api.sim.cups[1].held,false);
canvas.emit('keydown',{key:'3'});canvas.emit('keydown',{key:'ArrowLeft'});frame();assert.equal(api.sim.cups[2].held,true);canvas.emit('keydown',{key:' ',repeat:false});frame();assert.equal(api.sim.cups[2].held,false);
pointer(3,740,160);listeners.blur();assert.equal(api.sim.cups[0].held,false);
const leaf=api.sim.leaves[0];pointer(4,leaf.x,leaf.y);pointer(4,640,500,'pointermove');frame();assert.ok(leaf.held);assert.ok(Math.abs(leaf.y-500)<1);canvas.emit('pointerup',{pointerId:4});assert.equal(leaf.held,false);
pointer(5,340,320);pointer(6,1110,320);const zoom=api.renderer.zoom;pointer(6,1320,320,'pointermove');assert.ok(api.renderer.zoom>zoom);canvas.emit('pointerup',{pointerId:5});canvas.emit('pointerup',{pointerId:6});
element('time').value=1320;element('time').emit('input');frame(300);assert.equal(api.getState().minute,1320);assert.equal(api.getState().cycling,false);assert.equal(api.getState().night,1);element('time').value=600;element('time').emit('input');frame(300);assert.equal(api.getState().night,0);assert.equal(api.wildlife.night,0);
canvas.emit('keydown',{key:'1'});canvas.emit('keydown',{key:' '});context.document.hidden=true;listeners['document:visibilitychange']();assert.equal(api.sim.cups[0].held,false);const before=api.sim.time;frame(100);assert.equal(api.sim.time,before);context.document.hidden=false;listeners['document:visibilitychange']();frame(2);assert.ok(api.sim.time-before<.03,'No backlog after visibility restore');
api.wildlife.eggDone=true;api.wildlife.eggUntil=api.wildlife.time+24;frame();assert.equal(element('egg').hidden,false);element('time').value=990;element('time').emit('input');frame(1200);assert.equal(element('egg').hidden,false,'Signature still visible after twenty seconds and time change');frame(270);assert.equal(element('egg').hidden,true);
vm.runInContext(fs.readFileSync(__dirname+'/assets/audio-data.js','utf8'),context);for(const name of ['water-pour','metal-drips'])assert.deepEqual(Buffer.from(context.window.Tinwater.audioData[name],'base64'),fs.readFileSync(__dirname+'/assets/'+name+'.mp3'));
console.log('PASS: simultaneous touch holds, drag, pointer cancel/lost capture, keyboard hold/release, blur, leaf dragging, pinch, time hold, hidden-tab pause, 24-second visible signature, exact offline recordings.');
