(function(T){
  'use strict';
  const $=id=>document.getElementById(id),canvas=$('scene'),sim=new T.GardenPhysics(),renderer=new T.GardenRenderer(canvas),wildlife=new T.Wildlife(),audio=new T.GardenAudio(),pointers=new Map();
  const prefs={get(k,f){try{return localStorage.getItem('tinwater-'+k)??f;}catch{return f;}},set(k,v){try{localStorage.setItem('tinwater-'+k,v);}catch{}}};
  let minute=Number(prefs.get('time',990)),cycling=prefs.get('cycling','true')==='true',reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,selected=-1,last=0,acc=0,pinch=null,hintUntil=0,lastUI=-1;
  minute=Number.isFinite(minute)?T.clamp(minute,0,1439):990;audio.volume=T.clamp(Number(prefs.get('volume',.65))||0,0,1);$('volume').value=audio.volume*100;$('gentle').checked=reduced;
  function hint(text){$('hint').textContent=text;hintUntil=sim.time+6;}
  function darkness(m){const h=m/60;if(h>=7&&h<17)return 0;if(h>=17&&h<20)return (h-17)/3;if(h>=20||h<4.5)return 1;return 1-(h-4.5)/2.5;}
  function controls(){const h=Math.floor(minute/60),m=Math.floor(minute%60),night=darkness(minute);$('time').value=Math.floor(minute);$('time-label').textContent=`${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'am':'pm'}`;$('time-icon').textContent=night>.6?'☾':'☀';$('cycle').textContent=cycling?'Ⅱ':'▷';$('cycle').setAttribute('aria-pressed',String(cycling));$('cycle').setAttribute('aria-label',cycling?'Hold this time of day':'Resume day and night cycle');document.body.classList.toggle('night',night>.6);$('mood').textContent=night>.75?'after dark, another little world':h<8?'first light, waking slowly':h<12?'morning in the weeds':h<17?'late afternoon, unhurried':'dusk slips into the garden';}
  function local(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
  function cupAt(p){let hit=null,best=Infinity;for(const c of sim.cups){const dx=p.x-c.x,dy=p.y-c.y,x=dx*Math.cos(c.angle)+dy*Math.sin(c.angle),y=-dx*Math.sin(c.angle)+dy*Math.cos(c.angle);const pad=Math.max(13,21/renderer.scale);if(Math.abs(x)<c.w+pad&&y>-57-pad&&y<31+pad&&Math.hypot(dx,dy)<best){hit=c;best=Math.hypot(dx,dy);}}return hit;}
  function pointerDown(e){if(e.button!==0&&e.pointerType==='mouse')return;const screen=local(e),p=renderer.point(screen.x,screen.y);canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);const leaf=sim.leaves.find(l=>Math.hypot(p.x-l.x,p.y-l.y)<Math.max(28,20/renderer.scale)),cup=leaf?null:cupAt(p);const state={start:screen,last:screen,world:p,time:sim.time,moved:false,cup,leaf,startAngle:cup?.angle};pointers.set(e.pointerId,state);if(cup&&!cup.held){cup.held=true;cup.target=cup.angle;cup.velocity=0;selected=cup.id;renderer.selected=selected;hint('Hold the rim. Tip either way. Let go when you’re ready.');}else if(cup){state.cup=null;}if(leaf){leaf.held=true;hint('A leaf makes a very small boat.');}if(!cup&&!leaf){wildlife.disturb(p.x,p.y);}
    const bg=[...pointers.values()].filter(p=>!p.cup&&!p.leaf);if(bg.length===2){pinch={distance:Math.hypot(bg[0].last.x-bg[1].last.x,bg[0].last.y-bg[1].last.y)};}
  }
  function pointerMove(e){const screen=local(e),p=renderer.point(screen.x,screen.y),s=pointers.get(e.pointerId);if(!s){const c=cupAt(p);renderer.hover=c?.id??-1;canvas.style.cursor=c?'grab':sim.leaves.some(l=>Math.hypot(l.x-p.x,l.y-p.y)<30)?'grab':'default';return;}if(Math.hypot(screen.x-s.start.x,screen.y-s.start.y)>4)s.moved=true;
    if(s.cup){const c=s.cup,dx=(screen.x-s.start.x)/renderer.scale,dy=(screen.y-s.start.y)/renderer.scale,side=s.world.x<c.x?-1:1;c.target=T.clamp(s.startAngle+dx*.012+dy*.010*side,-1.64,1.64);}
    else if(s.leaf){s.leaf.x=T.clamp(p.x,30,T.W-30);s.leaf.y=T.clamp(p.y,60,900);s.leaf.angle=Math.sin(sim.time)*.1;}
    else{const bg=[...pointers.values()].filter(p=>!p.cup&&!p.leaf);if(pinch&&bg.length===2){s.last=screen;const distance=Math.hypot(bg[0].last.x-bg[1].last.x,bg[0].last.y-bg[1].last.y);renderer.zoomAt(distance/Math.max(1,pinch.distance),(bg[0].last.x+bg[1].last.x)/2,(bg[0].last.y+bg[1].last.y)/2);pinch.distance=distance;}else{renderer.pan.x+=screen.x-s.last.x;renderer.pan.y+=screen.y-s.last.y;renderer.layout();}}
    s.last=screen;
  }
  function pointerUp(e,cancel=false){const s=pointers.get(e.pointerId);if(!s)return;if(s.cup){s.cup.held=false;s.cup.velocity=T.clamp(s.cup.velocity,-2.5,2.5);if(!cancel&&!s.moved&&sim.time-s.time<.3){sim.tap(s.cup,s.world.x<s.cup.x?-1:1);audio.events(sim.events.slice(-1));}}if(s.leaf)s.leaf.held=false;pointers.delete(e.pointerId);pinch=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}
  canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',e=>pointerUp(e));canvas.addEventListener('pointercancel',e=>pointerUp(e,true));canvas.addEventListener('lostpointercapture',e=>pointerUp(e,true));canvas.addEventListener('wheel',e=>{e.preventDefault();const p=local(e);renderer.zoomAt(Math.exp(-e.deltaY*.001),p.x,p.y);},{passive:false});
  canvas.addEventListener('keydown',e=>{if(/^[1-6]$/.test(e.key)){selected=Number(e.key)-1;renderer.selected=selected;hint(`Cup ${selected+1}. Arrows tip; space holds or releases.`);e.preventDefault();return;}const c=sim.cups[selected];if(e.key==='Escape'){sim.releaseAll();pointers.clear();pinch=null;selected=-1;renderer.selected=-1;hint('Let it find its own rhythm.');}if(!c)return;if(['ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft'||e.key==='ArrowRight'){if(!c.held)c.target=c.angle;c.held=true;c.target=T.clamp(c.target+(e.key==='ArrowRight'?.18:-.18),-1.64,1.64);}if(e.key===' '&&!e.repeat){c.held=!c.held;c.target=c.angle;hint(c.held?'Holding. Space releases the cup.':'Released.');}});
  $('sound').addEventListener('click',async()=>{if(audio.enabled){audio.mute();$('sound-label').textContent='Sound off';$('sound').setAttribute('aria-pressed','false');}else{$('sound-label').textContent='Listening…';$('sound').setAttribute('aria-pressed','true');try{const ok=await audio.start();$('sound-label').textContent=ok?'Sound on':'Unavailable';if(!ok||audio.status==='partial')hint('Some sound recordings could not load. Try refreshing the garden.');}catch{$('sound-label').textContent='Try sound again';audio.mute();$('sound').setAttribute('aria-pressed','false');}}});
  $('volume').addEventListener('input',e=>{audio.setVolume(Number(e.target.value)/100);prefs.set('volume',audio.volume);});$('time').addEventListener('input',e=>{minute=Number(e.target.value);cycling=false;prefs.set('time',minute);prefs.set('cycling',false);controls();});$('cycle').addEventListener('click',()=>{cycling=!cycling;prefs.set('cycling',cycling);controls();});$('gentle').addEventListener('change',e=>reduced=e.target.checked);
  $('zoom-in').addEventListener('click',()=>renderer.zoomAt(1.3));$('zoom-out').addEventListener('click',()=>renderer.zoomAt(1/1.3));$('fit').addEventListener('click',()=>{renderer.zoom=renderer.minZoom;renderer.pan={x:0,y:0};renderer.layout();});
  function notes(open){$('field-notes').hidden=!open;$('about-toggle').setAttribute('aria-expanded',String(open));if(open)$('close-notes').focus();else $('about-toggle').focus();}$('about-toggle').addEventListener('click',()=>notes($('field-notes').hidden));$('close-notes').addEventListener('click',()=>notes(false));$('field-notes').addEventListener('keydown',e=>{if(e.key==='Escape')notes(false);});
  new ResizeObserver(()=>renderer.resize()).observe(canvas);window.addEventListener('blur',()=>{sim.releaseAll();pointers.clear();pinch=null;});document.addEventListener('visibilitychange',()=>{last=0;acc=0;sim.releaseAll();pointers.clear();pinch=null;if(document.hidden)audio.suspend();else audio.resume();});
  function frame(now){requestAnimationFrame(frame);if(document.hidden)return;const elapsed=last?Math.min(.08,(now-last)/1000):0;last=now;acc+=elapsed;while(acc>=1/120){sim.step(1/120);if(cycling)minute=(minute+2/120)%1440;wildlife.update(1/120,sim,darkness(minute),reduced);audio.events(sim.events);acc-=1/120;}audio.update(sim,darkness(minute));renderer.draw(sim,wildlife,darkness(minute),reduced);if(Math.floor(sim.time)!==lastUI){lastUI=Math.floor(sim.time);controls();if(sim.time>hintUntil&&hintUntil>0){hintUntil=0;$('hint').textContent='Tip a cup. Borrow a leaf. See where the water goes.';}}
    const eggVisible=wildlife.eggUntil>wildlife.time;$('egg').hidden=!eggVisible;if(eggVisible){const x=T.clamp(renderer.ox+955*renderer.scale-130,12,renderer.width-280),y=T.clamp(renderer.oy+490*renderer.scale,50,renderer.height-100);$('egg').style.left=x+'px';$('egg').style.top=y+'px';}canvas.dataset.audio=audio.status;canvas.dataset.selected=String(selected);canvas.dataset.holding=sim.cups.filter(c=>c.held).map(c=>c.id+1).join(',');canvas.dataset.egg=String(wildlife.eggDone);
  }
  controls();requestAnimationFrame(frame);
  // Explicit diagnostics for local physics, sound and browser verification.
  window.tinwater={sim,renderer,wildlife,audio,setTime(value){minute=T.clamp(value,0,1439);cycling=false;controls();},getState(){return{minute,cycling,reduced,night:darkness(minute),audio:audio.status,cups:sim.cups.map(c=>({id:c.id,angle:c.angle,volume:c.volume,held:c.held,tips:c.tips})),accounting:sim.accounting(),eggVisible:wildlife.eggUntil>wildlife.time};}};
})(window.Tinwater);
