/* Optional asset preparation, not a runtime build step. Bundles the two local
   CC0 MP3 files so double-click/file:// playback does not need fetch or a server. */
const fs=require('node:fs');
const path=require('node:path');
const data=Object.fromEntries(['water-pour','metal-drips'].map(name=>[name,fs.readFileSync(path.join(__dirname,'assets',name+'.mp3')).toString('base64')]));
fs.writeFileSync(path.join(__dirname,'assets','audio-data.js'),'/* CC0 sound sources and credits: ../README.md. Generated by pack-audio.cjs. */\nwindow.Tinwater.audioData='+JSON.stringify(data)+';\n');
console.log('Packed recordings for file:// playback.');
